### ISSUE TITLE
IMG mode/View: Error /media/pi/pi-power-tools: No such file or directory

### ISSUE THREAD

**Issue by dg-demers** [Botspot/Pi-Power-Tools#10]
In IMG mode, clicking the "View" button popped up a window titled "Error" and displaying the message, "/media/pi/pi-power-tools: No such file or directory."

But then, thinking it might help PPT to function, I manually created this folder. After that a pcmanfm file manager window popped up (as well as another window titled "Viewing IMG" and saying "Close this when you are finished viewing the files") open to this folder, but the folder was empty. 

The virtual machine ("Boot" button) seemed to work well enough, although I think it was not using the folders for its files that your scripts designated for it. I downloaded the latest raspbian image in PPT before I did these things. And so far, these are the only functions of PPT that I tried.

This is on a recently bought RPi 4 Model B Rev 1.4 with the latest Raspberry Pi OS dated 2020-08-20.

One complication: For security purposes I created a second user as which I did all these things. This second user is in all the same groups as the pi user. I "retired" --- meaning I am no longer routinely using --- the pi user account. But I did not delete it, although I changed its password. Also, both these users are now required to provide their passwords to sudo.

I did not try to, and would rather not be required to, use Pi Power Tools as the default pi user. So just in case using my second user account is the cause of these errors, I hope you will be able to modify your code so that I can.

**Comment by Botspot** [comment]
That new user you created seems to be the issue.
Does your new user have passwordless `sudo` ability?

**Comment by Botspot** [comment]
Oh, looks like you already answered my question.

> One complication: For security purposes I created a second user as which I did all these things. Also, both these users are now required to provide their passwords to sudo.

That's your problem right there - your non-root user must have passwordless `sudo` capability. The GUI must be run by a non-root user, but many commands the GUI runs must be run as root. Therefore my only option is to use `sudo` excessively in the script.

I'd be open to ideas on how to fix it. One solution I tried once was `gksudo`, which uses a password input GUI to `sudo`ify commands. But the nasty side-effect with that was having to type your password like 3 times in a row, which totally defeats the point.

**Comment by dg-demers** [comment]
> But the nasty side-effect with that was having to type your password like 3 times in a row

Well, that's exactly what happened --- three terminal windows popped up requiring a password which I provided --- when I clicked "Boot" and successfully ran Vdesktop with .img file.

Not an expert, but I might have seen this issue addressed somewhere, maybe in Stack Exchange. Anyway, I'm hoping there's some kind Linux magic that will make this work 'cause I really don't want to go back to no password sudo.

**Comment by Botspot** [comment]
It's likely possible I could modify PPT to require only one single password-entry upon launch. However, I don't think it's worth my time, as it works fine on stock passwordless-sudo Raspbian.
Additionally, doing that would force 100% of users to enter a password upon every launch. (like gparted)

Here's what I recommend you do: run each gui script from a terminal from the very start.
For IMG Mode: `~/Pi-Power-Tools/img-mode`
For USB Mode: `~/Pi-Power-Tools/usb-mode`
Then, every time `sudo` is invoked by a script, you will need to enter the password.

You can also attempt to run each script as root, though you're on your own if you encounter any issues.

**Comment by dg-demers** [comment]
I appreciate your help @Botspot, thank you. Though I haven't tried tried your suggestion yet.

> It's likely possible I could modify PPT to require only one single password-entry upon launch. However, I don't think it's worth my time,

I might see how far I could go myself trying to rewrite your script—if I ever get VERY ambitious.

**Comment by Botspot** [comment]
Rewriting it wouldn't be that hard.
If I were to do it, I'd run every script as `sudo`, and see how well each one works. Any problems that crop up would probably be easy to correct.
For example, if a certain command won't run well as `root`, just append `sudo -u pi` to the beginning of it.
