### ISSUE TITLE
Fatal Error: Failed to expand image

### ISSUE THREAD

**Issue by DRAGxMEx2xHELL** [Botspot/Pi-Power-Tools#11]
Hi 

Did a fresh install of Pi Power Tools, tried backing up one of my images, but i get a error at the end saying Failed to Expand Image. Not sure whats causing this, my USB Drive has more then enough space.

**Comment by Botspot** [comment]
What kind of partition is on your usb drive? If it's fat32, then there's your problem.

(fat32 filesystems are not able to hold anything larger than 4GB)

**Comment by DRAGxMEx2xHELL** [comment]
No its Exfat for that reason

**Comment by DRAGxMEx2xHELL** [comment]
Yes i have the scripts to mount exfat

**Comment by Botspot** [comment]
I need some more details.  

- You say you "tried backing up one of my images". Specifically which button did you click?
- Could you also post the entire terminal output? Giving me a "Fatal Error: Failed to expand image" is not enough.

**Comment by Botspot** [comment]
After posting two screenshots, I determined that the cause of this error was the OP trying to backup his image to an ExFAT storage device.  
It was verified that this was the cause of the problem, because IMG-from-SD successfully made a backup to /home/pi on his RPi.

Mystery solved, issue closed.
