### ISSUE TITLE
Networking

### ISSUE THREAD

**Issue by Xelendor1** [Botspot/Pi-Power-Tools#12]
Any way to add networking to the virtual machine? right now mine is stuck without an IP or network interface...

**Comment by Botspot** [comment]
Networking should work out of the box. However the panel indicator will not display any network interfaces because of how the passthrough is set up.

In your virtual machine, try pinging google:
```
ping google.com
```

**Comment by Xelendor1** [comment]
I see, internet worked, was trying to use it as a sort of vm, ended up figuring out how to use docker instead. cheers

**Comment by Botspot** [comment]
> I see, internet worked, was trying to use it as a sort of vm, ended up figuring out how to use docker instead. cheers

What were you trying to do that vdesktop couldn't do?
