### ISSUE TITLE
raspbian lite option

### ISSUE THREAD

**Issue by umsaenga** [Botspot/Pi-Power-Tools#16]
Hi, any chance of adding this for raspbian lite? or maybe it is, how to run on CLI?

regards.

**Comment by spectrumgamer75** [comment]
Is it the latest raspberry pi os buster lite? If yes the it will run as I am also running lite.

**Comment by umsaenga** [comment]
yes, [latest](https://downloads.raspberrypi.org/raspios_lite_armhf/release_notes.txt)

> If yes the it will run as I am also running lite.

Great, what is the commands? I look through [readme](https://github.com/Botspot/Pi-Power-Tools/blob/master/README.md) and only find GUI instructions

**Comment by spectrumgamer75** [comment]
The app is meant for gui, when I tried to run it via ssh it said "unable to detect display"

**Comment by umsaenga** [comment]
> 
> 
> The app is meant for gui, when I tried to run it via ssh it said "unable to detect display"

as per my original question:

> 
> 
> Hi, any chance of adding this for raspbian lite? or maybe it is, how to run on CLI?
> 
> regards.

maybe I wait for owners to provide insight

**Comment by spectrumgamer75** [comment]
I have notified @Botspot, he will get to you shortly

**Comment by Botspot** [comment]
> Hi, any chance of adding this for raspbian lite? or maybe it is, how to run on CLI?
> 
> regards.

There is not a standalone, interactive, CLI script for Pi Power Tools. But, most of the functions in PPT are in their own separate scripts.  
For example, the virtual machine is CLI-based and works fine from the console.
Most other PPT scripts (like shrink, backup, etc) are cli-based.

So you will still be able to use some functionality of PPT. Is there anything in particular you're trying to do, @umsaenga?

**Comment by umsaenga** [comment]
Thank you for insightful answer..

The link you provided answers the question, looking to do manual backups from time to time from within CLI, will give the instructions a try and revert back should there be any further questions.
Regards.
