### ISSUE TITLE
No writing SD image on mounted remote disk

### ISSUE THREAD

**Issue by Rooby69** [Botspot/Pi-Power-Tools#17]
I would like to write an SD image on a mounted remote disk but it is not possible since there is no available space.
I guess the available space could not be detected on remote mounted devices.

**Comment by Botspot** [comment]
Details requested:

- Are you trying to **flash** the mounted disk?
- And what do you mean by "**remote** disk"?

**Comment by Rooby69** [comment]
I have a USB stick in my router (10.10.1.1) and I want to backup on this USB stick (NTFS formatted).
On the router I enabled the samba share for the USB stick.
On the raspberry I set in /etc/fstab to mount this share at boot:
//10.10.1.1/backup /media/router cifs vers=2.0,username=user,password=,pass-systemd.automount,x-systemd.requires=network-online.target,file_mode=0777,dir_mode=0777, x-systemd.automount 0 0
This works well using a script to backup the SD card using dd but unfortunately not using PI-Power-Tools because of no availiable space. But there is enough space on this share.

**Comment by Botspot** [comment]
I'm surprised you were able to directly write to that USB drive using anything. Most routers, cloud storage, and samba shares will share just the filesystem, not raw 1's and 0's. (or partitions, or partition tables)

So I am stumped at how you're able to directly flash partitions to the USB device over a Samba Share. That shouldn't work.

As far as getting this "fixed", I am not sure how to help. Somehow, I'd need to replicate your setup, which would likely be impossible without spending money to buy the same router you're using.

**Comment by Rooby69** [comment]
Maybe I was not clear enough I just wanted to backup my raspberry (while running) to an image file (*.img) on the smba share of my router.

**Comment by Botspot** [comment]
> Maybe I was not clear enough I just wanted to backup my raspberry (while running) to an image file (*.img) on the smba share of my router.

Oh! To an img. That's a different story.

Pi Power Tools uses a drastically different strategy than `dd`. Instead of directly writing ones and zeros to an image, Pi Power Tools conserves space by incrementally copying files to the image. This approach saves space, and after making your first backup, saves time.

Over a network, through a samba share, I have no idea how the image can be mounted, or resized. It's probably impossible.

**Comment by Rooby69** [comment]
The .img created by dd on samba share was possible to mount and viewing the content by the pi power tools. That was not an issue. But I wanted to create  .img file by pi power tools this was not possible. (No space left.)
I only wanted to create an img file to backup the whole SD card. In case of a defect card I can flash a new one using this backup.

**Comment by Botspot** [comment]
It's probably the image shrinking and expanding that's causing problems.

**Comment by Rooby69** [comment]
I think checking the space left for writing the image file will not work since it is a samba share and no local storage. Maybe the left space cannot be calculated. Could it be possible to skip this just writing the image without checking?

**Comment by Botspot** [comment]
I don't have any network shares to test on, so unfortunately I'm not able to help.

@Rooby69, if you're still trying to do this, consider changing the scripts yourself until it works. Once you've determined what works, I can try to implement some or all of your changes.

Thank you.
