### ISSUE TITLE
Unable to boot image from usb

### ISSUE THREAD

**Issue by timrowledge** [Botspot/Pi-Power-Tools#2]
Loaded Pi-Power-Tools on a Pi 4/4.
Inserted uSD card from a working Pi (boots to desktop etc with no problems).
Run Pi-Power-Tools
Choose USB; select device ok
Click Boot
Boot Console opens - many lines of log etc.
Gets to {hostname} login:
Nothing happens after that whether I leave it, enter the actual password, or even the default 'raspberry' password.
What info would help debug this?

**Comment by Botspot** [comment]
> a working Pi boots to desktop etc with no problems
Is the SD card Raspbian? Did you happen to change your hostname to something other than `pi@raspberrypi`?

**Comment by timrowledge** [comment]
Yes, the SD card has a working Raspbian 2020-03-02 image.
The hostname is SmartiPi because it lives in a SmartiPi case and I try to set host names that give me some clue which Pi it is (I have dozens).
The username is still pi.

As an experiment I fired it up 'proper;y' and set the hostname back to raspberrypi; I can now install it in a card reader on my Pi4, do the USB/Boot thing and it starts and logs in ok - but still no desktop. I can do cmdline stuff ok.

One possible issue that just ocurred to me - I run all my Pi via VNC. Thus I am looking at the Pi4 via VNC and maybe there is some interaction that prevent the VDesktop window from working? Insane or genius?
I've attached the boot log output in case it makes any sense.

**Comment by timrowledge** [comment]
OK; a Terrible Warning To U All.

Never (and I mean this seriously) hack before being adequately caffeinated in the morning.
Whilst trying things yesterday I had set the preference to boot to console istead of desktop. Sigh.

Now I get a desktop. It is very slow. I can't actually run (original)Scratch, for example.
However, the raspi-config ran well enough to return the host name to SmartiPi and when replaced in the actual SmartiPi machine the hostname was correct.

So I think there may be some fix needed to cope with hostnames not bein the default or at least a check and helpful error message.

**Comment by Botspot** [comment]
Glad you have it solved!

> It is very slow. I can't actually run (original)Scratch, for example.

That is to be expected, as there are several more bottlenecks introduced. Still way faster than emulation, though.
[Graphics are slow](https://github.com/Botspot/vdesktop/issues/3) because OpenGL doesn't work through Xephyr. And other bottlenecks.

I'll update Vdesktop to boot properly on guests whose hostname is not raspberrypi.

FYI: in your log it shows you tried to run `startx`. That won't work since **your host system is already running an X server**. To get around this, `vdesktop` launches a second X server (`Xephyr`), and then makes the guest's desktop session connect to it via the `~/.profile` file.

Until I fix Vdesktop, you can launch the desktop yourself by pasting this into the Boot Console:

    export DISPLAY=:1
    eval "/usr/bin/lxsession -s LXDE-pi -e LXDE; sleep 10; /usr/bin/lxsession -s LXDE-pi -e LXDE" &
    sleep 10
    eval "pcmanfm --desktop --profile LXDE-pi; sleep 20; pcmanfm --desktop --profile LXDE-pi" &
    lxpanelctl restart
    sleep 10
    lxpanelctl restart

**Comment by Botspot** [comment]
Vdesktop has been updated to fix the hostname problem.
Two ways to apply the update:
 - Next time you click Boot, the Boot Console will ask permission to update. Just press Enter.
 - On the main PPT window, enable the Update button via Settings, then click Update. This will erase imglist and all other configs, though. The choice is yours.

**Comment by timrowledge** [comment]
Excellent; that seems to work fine. Thanks for the fast repair!
