### ISSUE TITLE
Kali Linux

### ISSUE THREAD

**Issue by slashtechno** [Botspot/Pi-Power-Tools#20]
Hi, could you please add Kali Linux to Pi Power Tools? Is it possible to add both without the desktop environment and with. This would allow a simple way to penetration test without installing Kali Linux on a new SD card.

Thanks

**Comment by Botspot** [comment]
Pi Power Tools does not support tar.xz image downloads. If someone would like to add support and  submit a Pull Request, I'd consider adding it to Pi Power Tools.

Kali Linux downloads page:  
https://www.offensive-security.com/kali-linux-arm-images/
