### ISSUE TITLE
Drag and dropping files not working with thunar

### ISSUE THREAD

**Issue by mobilegmYT** [Botspot/Pi-Power-Tools#23]
When trying to drag and drop an IMG file from thunar into the IMG Mode screen, it shows that little hand that indicates it can be dropped, but nothing happens.

**Comment by Botspot** [comment]
If no text gets dropped into the text box from Thunar, then there's nothing I can do about it unless I go submit a PR for Thunar.

Drag and drop is only tested on RPiOS's default file manager, `pcmanfm`.
