### ISSUE TITLE
Got some errors and it didn't install; it's not in the start menu.

### ISSUE THREAD

**Issue by bassamanator** [Botspot/Pi-Power-Tools#3]
```$wget -O - https://raw.githubusercontent.com/Botspot/Pi-Power-Tools/master/update | bash
--2020-07-29 22:10:51--  https://raw.githubusercontent.com/Botspot/Pi-Power-Tools/master/update
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1606 (1.6K) [text/plain]
Saving to: 'STDOUT'

-                                100%[========================================================>]   1.57K  --.-KB/s    in 0s      

2020-07-29 22:10:51 (4.80 MB/s) - written to stdout [1606/1606]

rm: cannot remove '/home/pi/logo-64.png': No such file or directory
--2020-07-29 22:10:51--  https://raw.githubusercontent.com/Botspot/Pi-Power-Tools/master/icons/logo-64.png
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.192.133, 151.101.128.133, 151.101.64.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.192.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2760 (2.7K) [image/png]
Saving to: 'logo-64.png'

logo-64.png                      100%[========================================================>]   2.70K  --.-KB/s    in 0s      

2020-07-29 22:10:52 (10.5 MB/s) - 'logo-64.png' saved [2760/2760]

Cloning into 'Pi-Power-Tools'...
remote: Enumerating objects: 160, done.
remote: Counting objects: 100% (160/160), done.
remote: Compressing objects: 100% (156/156), done.
remote: Total 495 (delta 92), reused 5 (delta 1), pack-reused 335
Receiving objects: 100% (495/495), 8.33 MiB | 992.00 KiB/s, done.
Resolving deltas: 100% (253/253), done.
cp: cannot stat '/home/pi/Pi-Power-Tools.old/data/imglist': No such file or directory
cp: cannot stat '/home/pi/Pi-Power-Tools.old/data/ziplist': No such file or directory
```

**Comment by Botspot** [comment]
Nothing in that output looks wrong. Those `cp` errors and the `rm` errors are normal for a first-time installation. Your terminal output was identical to mine, except that yours never mentioned it was downloading vdesktop. Strange.

Does the folder `/home/pi/Pi-Power-Tools` exist? If so, does the folder `/home/pi/Pi-Power-Tools/vdesktop` exist?

Did you see any window pop up during installation? (You should see a little progress bar window titled "PPT Installer")
If you didn't see that window, then post the output of:
`apt search zenity`
And if it turns out `zenity` is not installed already, then I'm going to need more info on what OS you're running.

**Comment by bassamanator** [comment]
**Does the folder /home/pi/Pi-Power-Tools exist? If so, does the folder /home/pi/Pi-Power-Tools/vdesktop exist?** It did before I deleted it. 

I installed this on on my RPi4 btw.

I wasn't able to start the GUI manually btw but I imagine this tool is to be installed on a 'mother' system, that is, not on your rpi.

```
▓ ~ ▓▒░ apt search zenity                                                            ░▒▓ 100 ✘  13s  pi@rpi  12:42:55 AM ▓▒░
Sorting... Done
Full Text Search... Done
debian-buster-64/testing 20200219-1 armhf
  Debian Buster arm64 bootable image for systemd-nspawn

debian-goodies/stable 0.84 all
  Small toolbox-style utilities for Debian systems

gmtkbabel/stable 0.1-1 all
  graphical interface for mtkbabel

libui-dialog-perl/stable 1.21-0.1 all
  UI::Dialog a wrapper for various dialog applications

mate-dialogs/stable 1.8.0+dfsg1-2 armhf
  Display graphical dialog boxes from shell scripts

mate-dialogs-common/stable 1.8.0+dfsg1-2 all
  Display graphical dialog boxes from shell scripts (common files)

mate-dialogs-dbg/stable 1.8.0+dfsg1-2 armhf
  Display graphical dialog boxes from shell scripts (debugging symbols)

octave-zenity/stable 0.5.7-9 all
  simple graphical user interfaces using zenity in Octave

python-vsgui/stable 0.3.3-1 all
  Very Simple Graphical library for Python shell script

ssft/stable 0.9.17 all
  Shell Scripts Frontend Tool

yad/stable 0.40.0-1 armhf
  tool for creating graphical dialogs from shell scripts

zenity/stable,now 3.30.0-2 armhf [installed]
  Display graphical dialog boxes from shell scripts

zenity-common/stable,now 3.30.0-2 all [installed,automatic]
  Display graphical dialog boxes from shell scripts (common files)
```

**Comment by Botspot** [comment]
> I imagine this tool is to be installed on a 'mother' system, that is, not on your rpi.
Actually, PPT is only meant to be installed on a RPi.

OK, it looks like Zenity is installed.

> I wasn't able to start the GUI manually btw
? You were in the graphical RaspbiOS desktop when you ran the install command, weren't you? (You need to be. It won't work if you run it in the console.)

**Comment by Botspot** [comment]
Any updates?

**Comment by bassamanator** [comment]
Forgot about this actually.

So I just installed again while connected via VNC. Worked just fine this time. I was also able to load and boot into an image that I had created a few weeks back using image-backup (I think pi-power-tools using this app as well). I wasn't able to boot to desktop; I didn't see that option. BTW if I boot an image and make changes to it, will they be saved?

In any case, this is a very useful tool that you're created here. Will explore it some more.

**Comment by Botspot** [comment]
Good to know things are solved for you.
PPT should boot to desktop by default. If it doesn't, either the img you're trying to boot is **modified** in some way, or it's RaspiOS **Lite** that doesn't ship with a GUI by default.
And yes, any changes you make inside are preserved.

**Comment by Mynt** [comment]
Got the same error, arrived here, got the same solution, maybe it could be useful to warn that installation must be run from a terminal within the graphical desktop.
