### ISSUE TITLE
Support for Raspberry Pi OS Bullseye

### ISSUE THREAD

**Issue by K-MTG** [Botspot/Pi-Power-Tools#32]
Raspberry Pi OS Bullseye does not appear to be compatible with Pi Power Tools.

**Comment by Botspot** [comment]
Exactly what doesn't work?

I don't use PPT much anymore, but I have used it on my Bullseye system for booting a few images and mounting some partitions.

**Comment by K-MTG** [comment]
I tried expanding the file system but got a `Filesystem appears corrupted` error

**Comment by Botspot** [comment]
> I tried expanding the file system on a Bullseye image but got a `Filesystem appears corrupted` error

I've used PPT a lot lately and have expanded multiple OS-images with it. And I never got that error.
So most likely the problem was caused by corrupted data inside the image or something.
