### ISSUE TITLE
Downloading update... bash: line 2: $'[?25h[0KDone': command not found

### ISSUE THREAD

**Issue by thewaver007** [Botspot/Pi-Power-Tools#37]
Hi, trying to install Pi-Power tools but get following error:

OS: Raspbian GNU/Linux 10 (buster)
OS architecture: 32-bit
Last updated Pi-Apps on: 07/27/2022
Latest Pi-Apps version: 07/27/2022
Kernel: armv7l 5.10.103-v7+
Device model: Raspberry Pi 3 Model B Plus Rev 1.3
Cpu name: Cortex-A53
Ram size: .92 GB
Raspberry Pi OS image version: 2019-07-10
Language: en_US.UTF-8

BEGINNING OF LOG FILE:
-----------------------

Will install these packages: yad systemd-container xserver-xephyr expect 
Creating an empty apt-package to install the necessary apt packages...
It will be named: pi-apps-7144246a
Depends: expect, systemd-container, xserver-xephyr, yad
Running sudo apt update...
Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:2 https://deb.nodesource.com/node_14.x buster InRelease
Hit:3 http://archive.raspberrypi.org/debian buster InRelease
All packages are up to date.
apt update complete.
Installing the pi-apps-7144246a package...
The following additional packages will be installed:
  expect tcl-expect
Suggested packages:
  tk8.6
The following NEW packages will be installed:
  expect pi-apps-7144246a tcl-expect
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Get:1 /home/pi/pi-apps-7144246a.deb pi-apps-7144246a all 1.0 [772 B]
Get:2 http://ftp.cica.es/mirrors/Linux/raspbian/raspbian buster/main armhf tcl-expect armhf 5.45.4-2 [121 kB]
Get:3 http://ftp.cica.es/mirrors/Linux/raspbian/raspbian buster/main armhf expect armhf 5.45.4-2 [166 kB]
Fetched 286 kB in 0s (673 kB/s)
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 120998 files and directories currently installed.)

Unpacking tcl-expect:armhf (5.45.4-2) ...

Unpacking expect (5.45.4-2) ...

Unpacking pi-apps-7144246a (1.0) ...

Apt finished.
Package installation complete.
Downloading update... bash: line 2: $'[?25h[0KDone': command not found

Failed to install Pi Power Tools!
◢◣Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu

Is this a known error where there is a fix ??
Kind regards
Don...

**Comment by Botspot** [comment]
Thank you for reporting this issue. This is an issue with Pi-Apps, I've been able to reproduce it, and I will fix it soon.

**Comment by Botspot** [comment]
Fixed with Pi-Apps commit https://github.com/Botspot/pi-apps/commit/bde43a3a7b167ea63100ce17210c6ce50cd1c1c1.

Thank you very much for reporting!

**Comment by thewaver007** [comment]
Hi Botspot, Many thanks for this program and fixing the error so quickly...
