### ISSUE TITLE
Errors opening lxde applications on Raspberry Pi OS lite

### ISSUE THREAD

**Issue by mtlynch** [Botspot/Pi-Power-Tools#4]
### Repro steps

Boot 2020-05-27-raspios-buster-lite-armhf.img (the clean Raspberry Pi OS lite build) in IMG mode

### Expected

Boot console shows a clean terminal

### Actual

Something seems to be attempting to launch several lxde applications:

```bash
-bash: /usr/bin/startlxde-pi: No such file or directory
-bash: lxpanelctl: command not found
-bash: pcmanfm: command not found
-bash: /usr/bin/startlxde-pi: No such file or directory
-bash: lxpanelctl: command not found
-bash: /usr/bin/startlxde-pi: No such file or directory
pi@raspberrypi:~ $ -bash: pcmanfm: command not found
-bash: /usr/bin/startlxde-pi: No such file or directory
-bash: /usr/bin/startlxde-pi: No such file or directory
```

The `-bash: /usr/bin/startlxde-pi: No such file or directory` repeats infinitely every 5 seconds or so.

**Comment by Botspot** [comment]
The Boot option, technically [Vdesktop](https://github.com/Botspot/vdesktop), does not detect what OS version you're trying to run.
By default, PPT tries to boot all imgs in GUI mode. (to desktop) Therefore, it will attempt to run those graphics-related executables, like lxsession, startlxde-pi, pcmanfm, lxpanel, etc. 
If you want to boot RaspiOS Lite, you need to go to [Settings](https://github.com/Botspot/Pi-Power-Tools#settings) and change the boot mode to "Boot to Console". You can choose to have it login automatically to the guest's console or not.
