### ISSUE TITLE
Sponsorship options

### ISSUE THREAD

**Issue by mtlynch** [Botspot/Pi-Power-Tools#5]
Is there a way to fund this project? It's likely useful for [my business](https://tinypilotkvm.com), so I'd be interested in funding its development.

**Comment by Botspot** [comment]
Hmm, I never expected to be asked this. I developed this software to make my life easier. And later figured I'd upload it to github in case others would find it useful.

Just curious: how would you use it in your business? Do you plan to reverse-engineer the code, and use it in your own application? Or do you plan to use it as intended, as a RaspiOS IMG manager?

Of course I wouldn't turn down "free" money, so if you feel like I deserve a little something, you can send it to paypal.me/josephmarchand.

**Comment by mtlynch** [comment]
>Just curious: how would you use it in your business? Do you plan to reverse-engineer the code, and use it in your own application? Or do you plan to use it as intended, as a RaspiOS IMG manager?

Haha, someone who's trying to steal your software isn't going to offer to donate to the project. Just sent a donation!

I sell a Pi kit that includes a modified version of Raspberry Pi OS. 

My current process looks like this:

1. Flash the stock RasPi OS Lite image to a microSD from a desktop.
1. Add the `ssh` file to enable SSH access when I insert it into the Pi (50% of the time, I forget to do this and have to bring it back to a PC again to add it)
1. Insert the microSD into a Pi and boot it up.
1. Configure the Pi with my software.
1. Shutdown the Pi.
1. Remove the microSD card.
1. Put the microSD into a PC to `dd` the image and then run PiShrink.

It's a pretty manual process and involves physically moving disks around a lot. I'd love to use PPT to reduce some of the manual effort involved.

**Comment by Botspot** [comment]
> Haha, someone who's trying to steal your software isn't going to offer to donate to the project.

I didn't mean "reverse-engineer" as in "steal". Instead, I was curious if you planned to re-use some bits and pieces for your own project - like maybe the virtual machine stuff, or my implementation of remote clipboard sync, which I see your product currently can't do.

> I sell a Pi kit that includes a modified version of Raspberry Pi OS.
> 
> My current process looks like this:
> 
> 1. Flash the stock RasPi OS Lite image to a microSD from a desktop.
> 2. Add the `ssh` file to enable SSH access when I insert it into the Pi (50% of the time, I forget to do this and have to bring it back to a PC again to add it)
> 3. Insert the microSD into a Pi and boot it up.
> 4. Configure the Pi with my software.
> 5. Shutdown the Pi.
> 6. Remove the microSD card.
> 7. Put the microSD into a PC to `dd` the image and then run PiShrink.
> 
> It's a pretty manual process and involves physically moving disks around a lot. I'd love to use PPT to reduce some of the manual effort involved.

I believe PPT will do all of that quite nicely to the image. One question though: it seems like you'd be doing all those steps only **once**, then duplicate that golden SD card to all the clone cards. But if streamlining your process is a priority for you, does that mean you have to perform all those steps repeatedly or something?

**Comment by mtlynch** [comment]
>One question though: it seems like you'd be doing all those steps only once, then duplicate that golden SD card to all the clone cards. But if streamlining your process is a priority for you, does that mean you have to perform all those steps repeatedly or something?

Right, it happens repeatedly. I'm currently creating a golden SD card image every time I cut [a versioned release](https://github.com/mtlynch/tinypilot/releases).
