### ISSUE TITLE
Support a CLI-only mode

### ISSUE THREAD

**Issue by mtlynch** [Botspot/Pi-Power-Tools#8]
I'd love to be able to drive PPT from the command-line. Specifically, I'm interested in a scenario like the following:

```bash
ppt-boot --img my-target.img --script my-script.sh
```

Where PPT boots `my-target.img` like a VM, executes `my-script.sh` in a bash shell, shuts down, and saves the resulting `.img` file.

How difficult would this be?

**Comment by Botspot** [comment]
Have you seen [Vdesktop](https://github.com/Botspot/vdesktop)? I developed vdesktop first, and then later decided to combine it with a few other image tools and wrap it all up in a GUI.

Vdesktop is completely command-line based, though at the moment it doesn't auto-run any scripts in the guest. That would be super easy to add though.

**Comment by mtlynch** [comment]
Oh, I hadn't seen that. That's even better! Should I move this feature request to that repo?

**Comment by Botspot** [comment]
Yes.
